baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'ssalggnikool'
theme = 'risotto'
sectionPagesMenu = 'main'

[params.about]
title = 'samara or (Me)'
logo = 'images/bwah.png'

[[params.socialLinks]]
icon = 'fa-brands fa-github'
title = 'GitHub'
url = 'https://github.com/ssalggnikool'

[[params.socialLinks]]
icon = 'fa-brands fa-twitter'
title = 'Twitter'
url = 'https://twitter.com/ssaIggnikool'

[[params.socialLinks]]
icon = 'fa-solid fa-envelope'
title = 'Mail'
url = 'mailto:flower@palera.in'

[params.theme]
palette = 'samie'